### ISSUE TITLE
 undefined method `to_msgpack' for Cql::TimeUuid & bignum too big to convert

### ISSUE THREAD

**Issue by Micka33** [msgpack/msgpack#188]
I have keywords that I store into cassandra using Cequel. When I want to `pack` it using `to_msgpack`,  I get the following error.

```
irb(main):024:0> Keywords.first.as_json.to_msgpack
NoMethodError: undefined method `to_msgpack' for #<Cql::TimeUuid:0x007fcf43dff830>
	from (irb):24:in `to_msgpack'
	from (irb):24
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Users/mickael/Documents/adwords-api/bin/rails:8:in `<top (required)>'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/commands/rails.rb:6:in `call'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:183:in `block in serve'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `fork'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'irb(main):025:0>
```

I understand what this error is about.  
I would suggest that to_msgpack call `as_json` when it can't `to_msgpack` in first place.
Because `#<Cql::TimeUuid:0x007fcf43dff830>.as_json` gives `{"n"=>81669062298108866050539035482603516879}`.
But then here is the thing `{"n"=>81669062298108866050539035482603516879}.to_msgpack` gives `RangeError: bignum too big to convert into 'unsigned long long'`.

```
irb(main):028:0> {"n"=>81669062298108866050539035482603516879}.to_msgpack
RangeError: bignum too big to convert into `unsigned long long'
	from (irb):28:in `to_msgpack'
	from (irb):28
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /Users/mickael/Documents/adwords-api/bin/rails:8:in `<top (required)>'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/commands/rails.rb:6:in `call'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/command_wrapper.rb:38:in `call'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:183:in `block in serve'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `fork'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/mickael/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by kuenishi** [comment]
This is rather an issue of Ruby library. Could you please reopen in https://github.com/msgpack/msgpack-ruby/issues ?
