### ISSUE TITLE
C# MessagePackMember Attribute Deserialize bug

### ISSUE THREAD

**Issue by germwire** [msgpack/msgpack#216]
[MessagePackMember(1, Name = "fees", NilImplication = NilImplication.MemberDefault)]
 public decimal Fees { get; set; }

ERROR:

{"The unpacked value is not expected type. Do not convert System.Byte (binary:0x0) MessagePackObject to MsgPack.MessagePackString."}
The unpacked value is not expected type. Do not convert System.Byte (binary:0x0) MessagePackObject to MsgPack.MessagePackString.
   at MsgPack.Serialization.DefaultSerializers.System_DecimalMessagePackSerializer.UnpackFromCore(Unpacker unpacker)
   at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker)
   at MsgPack.Serialization.UnpackHelpers.UnpackComplexObject[T](Unpacker unpacker, MessagePackSerializer`1 serializer, Int32 unpacked)
   at MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValueCore[TContext,TValue](Unpacker unpacker, TContext context, MessagePackSerializer`1 serializer, Int32 itemsCount, Int32 unpacked, Type targetObjectType, String memberName, Func`4 directRead, Action`2 setter)
   at MsgPack.Serialization.UnpackHelpers.UnpackValueTypeValue[TContext,TValue](UnpackValueTypeValueParameters`2& parameter)
   at MsgPack.Serialization.EmittingSerializers.Generated.####_Models_OrderSerializer1.UnpackValueOfprocessingFee(Unpacker , Order , Int32 , Int32 )
   at MsgPack.Serialization.UnpackHelpers.UnpackFromMapCore[TContext,TResult](Unpacker unpacker, TContext unpackingContext, Func`2 factory, IDictionary`2 operations)
   at MsgPack.Serialization.UnpackHelpers.UnpackFromMap[TContext,TResult](UnpackFromMapParameters`2& parameter)
   at MsgPack.Serialization.UnpackHelpers.UnpackFromMap[TContext,TResult](Unpacker unpacker, TContext context, Func`2 factory, IDictionary`2 operations)
   at MsgPack.Serialization.EmittingSerializers.Generated.####_Models_OrderSerializer1.UnpackFromCore(Unpacker )
   at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker)

**Comment by mlsomers** [comment]
You could try viewing your message with MsgPack Explorer (http://www.infotopie.nl/open-source/msgpack-explorer) If you get no errors there you might consider using the same lib in your project.

**Comment by drewnoakes** [comment]
This issue belongs on the [msgpack-cli repo](https://github.com/msgpack/msgpack-cli/issues).
