### ISSUE TITLE
was compiled against a different Node.js version using

### ISSUE THREAD

**Issue by weivea** [msgpack/msgpack#244]
Error: [egg-core] load file: /Users/weijianli/work/repos/caijing_stock_web/node_modules/byted-egg-metrics/app.js, error: The module '/Users/weijianli/work/repos/caijing_stock_web/node_modules/msgpack/build/Release/msgpackBinding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:678:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/weijianli/work/repos/caijing_stock_web/node_modules/msgpack/lib/msgpack.js:6:14)
    at Module._compile (module.js:649:30)/Users/weijianli/work/repos/caijing_stock_web/node_modules/egg/lib/application.js:59
      throw e;

re-compiling or re-installing can't fix this

**Comment by tagomoris** [comment]
You've created an issue on wrong repository: this repo is for MessagePack spec, not any implementations.
